% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[jou,a4paper]{apa6}

% Change font for whole document
\renewcommand{\familydefault}{\rmdefault}
\renewcommand*\rmdefault{bch}

% Add watermark for preprints at the top of each page
% Comment out to remove preprint watermark
%\usepackage{draftwatermark}
%\SetWatermarkText{PREPRINT}
%\SetWatermarkScale{0.3}
%\SetWatermarkAngle{0}
%\SetWatermarkVerCenter{25pt}
%\SetWatermarkColor[rgb]{0.85,0.85,0.95}

% Add header with journal information
\usepackage{fancyhdr}
\renewcommand{\headrulewidth}{0pt} 	% remove vertical line
\setlength{\headheight}{54pt}  % increase vertical space for header
\fancypagestyle{firststyle}
{
   \fancyhf{} % clear all header and footer fields
   
		\fancyhead[L]{\scriptsize  
		\textit{Meta-Psychology}, 2020, vol 4, MP.201X.xxx\\https://doi.org/10.15626/MP.\\Article type: Original Article\\Published under the CC-BY4.0 license \\
		\smallskip
%%%%%%%%%%%%%%%%%%%%%%%%%%%% Badges %%%%%%%%%%%%%%%%%%%%%
		\includegraphics[scale=0.2]{badges/opendata.png}
		\includegraphics[scale=0.2]{badges/openmaterial.png}
		\includegraphics[scale=0.2]{badges/preregestered.png}
		\includegraphics[scale=0.2]{badges/preregesteredplus.png}
		}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%		
    \fancyhead[C]{\scriptsize 
        Open data: Yes\\
        Open materials: Yes \\
        Open and reproducible analysis:\\
        Open reviews and editorial process: Yes\\
        Preregistration: 
        \vspace{0.5ex}
\\
		\smallskip}
    \fancyhead[R]{\scriptsize   Edited by: \\
        Reviewed by: \\
        Analysis reproduced by: \\
        All supplementary files can be accessed at OSF: \\
        https://doi.org/10.17605/OSF.IO/
        \vspace{0.5ex}
\\
		\smallskip}
}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\usepackage[]{graphicx}
\usepackage[]{color}
\usepackage{tikz}  % for watermark on first page

\usepackage{alltt}
\usepackage[american]{babel}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

\usepackage{amsmath}  	% for advanced math displays
\usepackage{booktabs}		% booktables

% With that package, tables are single spaced
\usepackage{setspace}

\usepackage{listings}  % for inline code blocks
\lstset{
	basicstyle=\footnotesize\ttfamily, % the size of the fonts that are used for the code
	breaklines=true,  % sets automatic line breaking
	breakatwhitespace=true % sets if automatic breaks should only happen at whitespace
}

\usepackage{url}	% links to headings
\usepackage{placeins} 	% flushes Figures before the next section starts
% use command \FloatBarrier

%% APA-style citations
\usepackage{csquotes}
\usepackage[backend=biber,style=apa,hyperref=true,giveninits,uniquename=init]{biblatex}
\DeclareLanguageMapping{american}{american-apa}

% TODO: Users must add their .bib file here
\addbibresource{LangWar.bib}

% remove unwanted fields from .bib-file
\AtEveryBibitem{	
  \clearfield{day}
  \clearfield{month}
  \clearfield{labelday}
  \clearfield{labelmonth}
}
%\usepackage{multicol} %unneeded, apa6 already split cols
\raggedbottom

\usepackage{hyperref} % should be loaded last as it redefines many Latex commands
\hypersetup{colorlinks, urlcolor=blue, citecolor=blue}

\usepackage{blindtext}


%========================================================================
%-----  Here starts the actual paper --------------------
%========================================================================

\title{The Language of War: A Conceptual Replication and Extension of Abe (2012) and Matsumoto and Hwang (2013)}
\shorttitle{LANGUAGE OF WAR}

\begin{document}
\thispagestyle{firststyle}  % Leave this for the journal's header
\authornote{\textit{Note}: Kayla N. Jordan is an Assistant Professor of Social Analytics at Harrisburg University of Science and Technology. Erin M. Buchanan is an Professor of Cognitive Analytics at Harrisburg University of Science and Technology. William E. Padfield is a Masters degree candidate at Missouri State University. Correspondence concerning this article should be addressed to Dr. Kayla N. Jordan, 326 Market St, Harrisburg, PA 17101. E-mail: kjordan@harrisburgu.edu}
\twocolumn[
    \vskip 23ex 
     {\centering   
%%%%%%%%%%%%%%%%%%%%%%%%%%% Title %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        {\Huge The Language of War: A Conceptual Replication and Extension of Abe (2012) and Matsumoto and Hwang (2013) \par}\vspace{3ex}
%%%%%%%%%%%%%%%%%%%%%%%%%% % Authors %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	    {\LARGE Kayla N. Jordan\par}\vspace{0.3ex}
	      \large Harrisburg University of Science and Technology\par\vspace{4ex}
	    {\LARGE Erin M. Buchanan\par}\vspace{0.3ex}
	      \large Harrisburg University of Science and Technology\par\vspace{4ex}
	    {\LARGE William E. Padfield\par}\vspace{0.3ex}
	      \large Missouri State University\par\vspace{4ex}  
	  }
{\centering\bfseries Abstract\par}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% ABSTRACT %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Legislative bodies have very important roles and understanding the psychology of their decision-making processes is a useful area of study. We add to this area by replicating two previous studies: Abe (2012) and Matsumoto and Hwang (2013) in the context of a legislative body. The present study hypothesized that legislators who support war measures would be externally focused and less cognitively complex in their speeches, while opponents of war measures would be internally focused. Speeches were obtained pertaining to the decisions for the U.S. to take military action in Kosovo, Iraq, and Libya. While we found mixed results depending on the circumstances of a specific conflict, we demonstrate how automated language analysis can be combined with voting records to better understand behavioral action, such as legislative decision.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\smallbreak

\medbreak
%%%%%%%%%%
\textit{Keywords}: language, war, congress, pronouns, verbs
\par\vspace{4ex}]

\section{The Language of War: A Conceptual Replication and Extension of Abe (2012) and Matsumoto and Hwang (2013)}

In the last few years, numerous civil disputes worldwide, which might threaten American interests and human rights, have spurred considerable debate over American military intervention. Despite declines in legislative control of foreign policy, the U.S. Congress still plays an important role in deciding how the military is used by retaining the rights to formally declare war, limit the use of military force, and control military appropriations (\cite{Phelps2002}). Previous research examined the predictors of presidential use of military force (\cite{Clark2005}; \cite{Keller2012}) and predictors of public support for war (\cite{Cohrs2002}; \cite{Friese2009}; \cite{McCleary2009}). However, the predictors of legislative support of military action have been understudied, thus presenting an interesting opportunity for exploration as well as replication of past studies in new contexts (\cite{Kriner2014}). Specifically, the current study examines linguistic styles as a predictor of support for war in the contexts of the U.S. Congress by conceptually replicating Abe (2012) and Matsumoto and Hwang (2013).

\subsection{Predictors of Support for Military Action}

While the current study focuses on linguistic style predictors of support, it is worth briefly reviewing past work on the various factors which predict support for war. When it comes to executive leaders like presidents, there is much variance across time and context, but some predictors emerge. For example, Keller and Foster (\citeyear{Keller2012}) found presidents high in internal locus of control to be more likely to engage in military conflict, and Leudar, Marsland, and Nekvapil (\citeyear{Leudar2004}) found executives engaging or planning to engage in conflict tended to use more us versus them rhetoric. Despite the executive making the ultimate decision to go to war, public opinion about the war is an important consideration for leaders (at least in a democracy). Furthermore, public opinion is generally easier to measure and has been the focus on much work not only in psychology but also in other fields like political science. Numerous studies have found robust predictors of support for war among citizens/voters including militarism, blind patriotism, and concern for national security (\cite{Cohrs2002}; \cite{Friese2009}; \cite{McCleary2009}).

Less work has been conducted exploring predictors of support for war among legislators. Kriner and Shen (\citeyear{Kriner2014}) did study ongoing support for the Iraq War by members of Congress and found opposition to the war generally related to the number of casualties from the member's home district. Beyond understanding how support for war changes through political rhetoric, it would also be useful to understand how legislators come to support war in the first place. In the wake of several incidences of the U.S. president acting alone to engage the nation in military conflict (i.e., the Vietnam War), Congress enacted the War Powers Act and sought to exert its power by forcing the president to consult with them and gain approval to keep the U.S. military fighting overseas. In other words, Congress becomes involved only after troops have begun fighting and must either vote in support of continuing U.S military involvement (as was the case for the Iraq War) or in opposition to the president's continued use of the military in the conflict (as was the case for the 1999 conflict in Kosovo and the 2011 Libyan conflict; Scigliano, 2017). We sought to expand past work in the area by using the debates and speeches about these votes given on the floor of Congress to predict how different members of Congress eventually voted to either support the president's use of military force or oppose it. As we use psychological text analysis to measure our predictors, the next section provides a brief overview on language analysis before we discuss the specific linguistic styles measured in the current study.

\subsection{Psychological Language Analysis}

Language, including political rhetoric, is the fusion of content and style words. Within any given sample of language, content words answer the question of what is being said, while style words answer the question of how it is being said. Content words include nouns, verbs, and adjectives, and style words include pronouns, prepositions, articles, conjunctions, negations, and quantifiers (\cite{Pennebaker2011}). The Linguistic Inquiry and Word Count program (LIWC2007; Pennebaker, Booth, \& Frances, 2007) is a text analysis software developed to summarize these types of words by breaking them down into 82 language categories. Besides style words, the LIWC measures constructs including: a) cognitive processes, such as \emph{know}, \emph{because}, and \emph{none} reflecting causation, exclusivity, and certainty, b) emotionality, which include words such as \emph{happy}, \emph{sad}, and \emph{angry}, c) relativity, such as \emph{go}, \emph{down}, and \emph{until} reflecting motion, space, and time, and d) personal concerns like money, death, and religion among others.

In many fields including social psychology, the LIWC analysis has become a common way to better understand psychological processes through the words people use. Tausczik and Pennebaker (\citeyear{Tausczik2012}) reviewed over 100 articles that used language as a basis for studying other constructs; specifically, these studies investigated how categories in the LIWC are related to psychological phenomena, such as attention, dominance, and deception. In the current investigation, we focus on attention as a potential mechanism for understanding how legislator's might work through decisions about war.

Just as a person's gaze can illuminate where their attention is so can the words they use. Specifically, pronouns and verb tense can demonstrate attentional focus by indicating who or what someone is attending to in a situation and how they are processing the situation. Therefore, greater use of first person pronouns indicates a self-focus, higher use of third person pronouns indicates a focus on others, and verb tense can indicate whether the focus was on past, present, or future events (\cite{Tausczik2010}). Attentional focus, in the form of pronouns, has been linked to depression (\cite{Rude2004}), bullying (\cite{Kowalski2000}), and marital satisfaction (\cite{Simmons2005}).

Another construct which can be automatically measured from language is cognitive complexity. Originally developed by Pennebaker and King (\citeyear{Pennebaker1999}), cognitive complexity measures the extent to which people are drawing distinctions between concepts and integrating ideas. In past studies, cognitive complexity has been found to be related to individual differences measures such as extroversion and conscientiousness (\cite{Pennebaker1999}), aggressive behaviors (\cite{Pennebaker2011}), and reactions to negative events (\cite{Abe2011}).

\subsection{Predicting Support from War from Linguistic Style}

We sought to conceptually replicate two studies of the role of linguistic style in predicting war attitudes and behaviors, Abe (\citeyear{Abe2012}) and Matsumoto and Hwang (\citeyear{Matsumoto2013}), in the U.S. Congressional context. Abe (\citeyear{Abe2012}) used linguistic analysis to examine the relationship between cognitive -- affective styles and support for the Iraq War in an online discussion forum. Consistent with past work, supporters of the war had a greater external focus and a more simplistic thinking style (Cohen's \(d\) \textasciitilde{} 0.35 to 0.41). Opponents of the war were more internally focused, showed greater cognitive processing, and used more negative emotion words. The current work seeks to conceptually replicate Abe (\citeyear{Abe2012}) with three changes: (1) extending to a new sample of Congressional speeches, (2) extending to additional conflicts in Kosovo and Libya, and (3) focusing solely on cognitive styles.

Matsumoto and Hwang (\citeyear{Matsumoto2013}) used speeches of world and political group leaders to more directly predict political aggression from language markers. Comparing speeches preceding violent acts of aggression to speeches preceding nonviolent acts of resistance against some outgroups, they found greater external focus (e.g., first person plural pronouns), less internal focus (e.g., first person singular pronouns), and lessened cognitive complexity before aggressive acts (Cohen's \(d\) \textasciitilde{} 0.67). The authors extend Abe (\citeyear{Abe2012})'s work into a wider political context predicting leader's actual decisions focusing on cognitive linguistic markers. The current work is a more direct replication of Matsumoto and Hwang (\citeyear{Matsumoto2013}) with the only substantive difference being the sample itself and the outcome measure (e.g., voting for war rather than actual acts of aggression). Given the variability between the two studies in terms of effect size magnitude and the generally small effects found for language studies, we sought generally to replicate the direction of the effects.

\subsection{Current Study}

The purpose of the current studies is to determine if past studies on war decisions and aggression replicate in the context of the U.S. Congress when voting on war measures. In the last few decades, Congress has had formal votes to authorize the president's use of military action three times. First, in 1999, U.S. allies intervened in a civil war in Serbia, and President Clinton asked Congress for formal approval to send U.S. military troops to assist U.S. allies. Second, in 2002, President Bush requested approval from Congress to continue military action against Iraq due to the supposed threat posed by their WMDs. Third, in 2011, President Obama sought approval to escalate U.S. military involvement in the Libyan civil war. In each of these cases, members of Congress (House and Senate separately) gave speeches opposing or supporting the president's request as well as engaged in debate with each other. The texts of these speeches and debates were analyzed to measure our linguistic style predictor variables. Members of Congress then formally voted (yay or nay) on whether or not to support the use of the U.S. military in each of these conflicts which was the basis of our binary outcome variable. As the study is a conceptual/far replication, successful replication for each hypothesis is defined as effects in the same direction where the confidence interval of the mean difference (i.e., Cohen's \(d_s\)) does not include zero.

\subsection{Hypotheses}

H1: Legislators supporting war measure will have an external focus and use more third person pronouns (particularly 3rd person plural pronouns) (\cite{Abe2012}; \cite{Matsumoto2013}).

H2: Legislators opposing war measure will have an internal focus and use more first person pronouns (\cite{Abe2012}).

H3: Legislators supporting wars measure will exhibit lower cognitive complexity than those opposing the measure (\cite{Matsumoto2013}).

\section{General Method}

\subsection{Language Samples}

Linguistic frequency analysis was conducted on political speeches gleaned from Congress. The source of language samples was the Congressional Record, a searchable database containing a record of each session of Congress since 1995 available at \url{https://www.congress.gov/congressional-record}, which is maintained by the U.S. Government Publishing Office. For this study, we searched for pertinent speeches from January 27, 1998 to September 19, 2013. Records were included if they pertained to U.S. relations with the following countries: Iraq, Libya, and Kosovo (see below for explanation of country selection). Samples were split by session date and person speaking, and therefore, each person could be represented multiple times in the dataset. Each file in the Congressional Record includes all speeches from the day selected, therefore, we separated each person's speeches by day into different files for processing. For example, a Senator may respond back and forth with an invited guest speaker, and all the Senators spoken words would be combined into one file for that day. Only Senators and Representatives were included in this analysis. These speeches were then coded for party affiliation of the Congressperson. All processed data, as well as an \emph{R} markdown document with data analysis scripts inline with this manuscript (\cite{Aust2017}) can be found at \url{https://osf.io/r8qp2/}.

\subsection{Variables}

\subsubsection{Language}

Each language sample was analyzed using the Language Inquiry and Word Count (\cite{Pennebaker2007}). The LIWC provides percentages of each individual text that fall into each category of words. We examined pronouns for Hypotheses 1 and 2. The pronouns category included first person singular and plural pronouns (\emph{I, me, we}), second person pronouns (\emph{you, your}), and third person singular and plural pronouns (\emph{he, she, they}). To measure external focus, third person singular and third person plural pronouns were added together. To measure internal focus, first person pronouns both singular and plural were added together. For Hypothesis 3, cognitive complexity was calculated using the same formula as Abe (2012). The LIWC categories of exclusives, negations, tentative words, and conjunctions were \emph{z}-scored and summed together.

\subsubsection{Military Action}

\begin{table}[htbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:summary-table}Summary of Voting Record by Chamber, Political Party, and Area of Conflict}

\begin{tabular}{ccccccccc}
\toprule
Study & \multicolumn{1}{c}{Conflict} & \multicolumn{1}{c}{Chamber} & \multicolumn{1}{c}{Number.Speeches} & \multicolumn{1}{c}{Votes.For} & \multicolumn{1}{c}{Votes.Against} & \multicolumn{1}{c}{Democrats.For} & \multicolumn{1}{c}{Republicans.For} & \multicolumn{1}{c}{Outcome}\\
\midrule
1A & Kosovo & House & 210.00 & 213.00 & 213.00 & 86\% & 16\% & Failed\\
1B & Kosovo & Senate & 49.00 & 58.00 & 41.00 & 93\% & 30\% & Passed\\
2A & Iraq & House & 274.00 & 296.00 & 133.00 & 40\% & 97\% & Passed\\
2B & Iraq & Senate & 138.00 & 77.00 & 23.00 & 58\% & 98\% & Passed\\
3 & Libya & House & 104.00 & 123.00 & 295.00 & 60\% & 6\% & Failed\\
\bottomrule
\end{tabular}

\end{threeparttable}
\end{center}

\end{table}

For the purpose of this study, military action was defined as military personnel being sent into another nation to coerce the actions of that nation. In the past 15 years, the U.S. has taken military action against Iraq, Afghanistan, Kosovo, and Libya, although Congress did not explicitly approve action in Afghanistan or Libya. Operational definitions for support for war were voting records (yay, nay) on bills authorizing military action for Iraq, Kosovo, and Libya (only voted on in the House). These bills were House Joint Resolution 114, 107th Congress (2002); Senate Concurrent Resolution 21, 106th Congress (1999); and House Joint Resolution 68, 112th Congress (2011). Oppose or support information was combined with the LIWC percentages described above. Table \ref{tab:summary-table} summarizes areas of conflict, number of speeches, and votes for each conflict by political party and the chamber of Congress.

\subsection{Data Analytic Technique}

The data collected include multiple language samples by the same member of Congress and are structured by both party affiliation and conflict region. Rather than analyze data from each conflict region and chamber of Congress together, we chose to analyze them separately in Studies 1A (House vote on Kosovo conflict), 1B (Senate vote on Kosovo conflict), 2A (House vote on Iraq conflict), 2B (Senate vote on Iraq conflict), and 3 (House vote on Libya conflict). The major reason for this was to conservatively test the robustness of any effects and to better demonstrate the reliability of the results. Another minor reason was to examine possible differences based on the unique circumstances of each conflict. The war in Iraq ostensibly involved a direct threat to the U.S. where the conflicts in Kosovo and Libya did not which could arguably impact how members of Congress talked about and voted on them.

This structure was best analyzed with multilevel modeling, which allowed us to control for the correlated error terms of member of Congress and party affiliation. We used the \emph{nlme} package to calculate the means and standard deviation for each variable by voting recording (Pinheiro, Bates, Debroy, Sarkar, \& Team, 2017). The intercept was used to predict the dependent variable (LIWC category percent), which creates a mean score for the dependent variable. Party affiliation and member of Congress were controlled as random intercept factors (Gelman, 2006). The standard error of the estimate was translated into standard deviation by multiplying by the square root of \emph{n} for the sample. This analysis was bootstrapped using the \emph{boot} library 1000 times, and the normal confidence interval for the mean was calculated using this function (Canty \& Ripley, 2017). These values were separated by voting record, Senate/House, and country of interest. The means and confidence intervals are presented in forest plots to show the relative percentages for each combination. The bootstrapped standard deviation values were used to calculate \(d_s\) values using the MOTE library with the pooled standard deviation as the denominator (Buchanan, Valentine, \& Scofield, 2017; Lakens, 2013). The \(d_s\) represents the effect size, or standardized mean difference, in each of the LIWC categories between members of Congress that voted for military action versus those that voted against it. Instead of using a traditional null-hypothesis test with \emph{p}-values, we examined if the bootstrapped confidence intervals of the effect size, \(d_s\), included zero. If the confidence interval included zero, this result would indicate no support for differences in the dependent variable for voting record, while confidence intervals that did not include zero indicated a difference in the dependent variable for voting record.

The decision to treat the voting record on the war measures (yay or nay for continuing military action) as the IV and the linguistics styles as the DVs despite our interest in predictor support for war was made for multiple reasons. First, while technically debate happens prior to the official voting, the majority of Congress people will have made up their minds hence the debate serves more as a justification for their decisions than as a persuasive function. Second, using the linguistic styles as the DVs is consistent with Abe (2012) which is one of the studies we sought to conceptual replicate.

\section{Study 1A - Kosovo in the House}

In early 1998, violence erupted in the Serbian region of Kosovo between ethnic Albanians and the Serbian government. A peace agreement later in the year lasted until the beginning of 1999 when several Albanian civilians were killed, prompting a resurrection of hostilities. When the Serbian government, namely President Slobodan Milosevic, failed to concede to allowing a NATO peacekeeping force in Kosovo during February 1999 negotiations, NATO authorized air strikes against Serbian targets. This decision subsequently prompted debate within the U.S. Congress as to the involvement of the U.S. military in NATO's operations in Serbia and Kosovo (\cite{Woehrel2006}).

In this study, we examine this debate in the U.S. House of Representatives to determine if members of Congress who supported U.S. military involvement focused on people or events differently than those who opposed it.

\section{Method}

Speeches made in the House of Representatives pertaining to the use of military force in Kosovo/Serbia were gathered from the Congressional Record available from the U.S. Government Publishing Office. In total, 210 speeches were collected. Speeches were limited to those made in the year preceding the vote on Senate Concurrent Resolution 21 made on April 28, 1999 to allow the President to conduct air and missile strikes against Yugoslavia (Serbia and Montenegro). This resolution failed in the House with 213-213 with 86\% of Democrats supporting the resolution and 84\% of Republicans opposing. These speeches were made by 156 unique speakers where where Republicans gave 108 speeches, Democrats gave 98 speeches, one Independent, one Non-Partisan, and two non-Representatives. Five speeches were excluded for no voting record. The average word count was 700.51 (\emph{SD} = 814.04).

\section{Results}

\begin{table}[htbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:Ktable}Descriptive statistics for each dependent variable by chamber for Kosovo}

\small{

\begin{tabular}{lccccccccc}
\toprule
Chamber & Hypothesis & DV & $M_O$ & $SD_O$ & $M_S$ & $SD_S$ & $d_s$ & $d_s$ LL & $d_s$ UL\\
\midrule
House & 1 & She/He & 0.52 & 0.70 & 0.55 & 0.90 & -0.03 & -0.31 & 0.24\\
House & 1 & They & 0.64 & 0.73 & 0.79 & 1.17 & -0.15 & -0.42 & 0.13\\
House & 1 & External & 1.16 & 1.14 & 1.33 & 1.37 & -0.13 & -0.41 & 0.14\\
Senate & 1 & She/He & 0.45 & 0.85 & 0.48 & 0.42 & -0.05 & -0.61 & 0.51\\
Senate & 1 & They & 0.81 & 0.72 & 0.53 & 0.42 & 0.48 & -0.09 & 1.04\\
Senate & 1 & External & 1.26 & 1.29 & 1.03 & 0.56 & 0.25 & -0.32 & 0.81\\
House & 2 & I & 1.86 & 1.40 & 2.32 & 1.97 & -0.27 & -0.54 & 0.01\\
House & 2 & We & 3.11 & 2.03 & 2.95 & 2.61 & 0.07 & -0.21 & 0.34\\
House & 2 & Internal & 4.98 & 2.50 & 5.26 & 3.34 & -0.10 & -0.37 & 0.18\\
Senate & 2 & I & 2.21 & 1.35 & 1.99 & 2.06 & 0.13 & -0.44 & 0.69\\
Senate & 2 & We & 3.15 & 2.06 & 1.53 & 0.64 & 1.09 & 0.48 & 1.69\\
Senate & 2 & Internal & 5.33 & 2.51 & 3.54 & 2.24 & 0.76 & 0.17 & 1.33\\
House & 3 & Complexity & 0.60 & 3.24 & -0.47 & 3.92 & 0.30 & 0.02 & 0.57\\
Senate & 3 & Complexity & 1.68 & 3.91 & -1.49 & 3.18 & 0.89 & 0.30 & 1.48\\
\bottomrule
\addlinespace
\end{tabular}

}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} Confidence intervals for $d_s$, which are standardized mean differences, were calculated using non-central $t$ distribution. O = Oppose, S = Support, LL = Lower Limit, UL = Upper Limit.}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}

\begin{figure}
\centering
\includegraphics{Language-of-War-Markdown_KJ2_files/figure-latex/Kpic-1.pdf}
\caption{\label{fig:Kpic}House (left) and Senate (right) bootstrapped means and 95\% confidence interval of each linguistic category for Kosovo.}
\end{figure}

A forest plot of the results can be found in Figure \ref{fig:Kpic}, and all descriptive statistics can be found in Table \ref{tab:Ktable}. Results only weakly supported Hypothesis 1. The trend is in the hypothesized direction with supporters of military action displaying greater external focus, but the effect is weaker in magnitude than in the original studies. Hypothesis 2 was not supported; legislators opposing the war measure did not display a greater internal focus (i.e., incorrect direction and magnitude of the hypothesized effect). In fact, supporters of the measure used more 1st person singular pronouns (e.g., I-words) contrary to our hypothesis. Hypothesis 3 was supported with supporters of the war measure showing lower cognitive complexity than those who opposed it and the magnitude of the effect was similar to the original studies.

\section{Study 1B - Kosovo in the Senate}

In the second part of this study, we examined the Kosovo debate in the U.S. Senate to determine if the differences found in the first part of the study replicate in a slightly different context.

\section{Method}

Speeches were gathered in the same manner as in the first part of the study. All speeches made in the Senate in the year before the March 23, 1999 vote on Senate Concurrent Resolution 21. This resolution passed the Senate with 58 supporting and 41 opposing. All but 3 Democrats supported the resolution while 70\% of Republicans opposed it. A total of 49 speeches were collected. These speeches were made by 25 unique senators with 12 speeches by Democrats and 37 by Republicans. The average word count for these speeches was 1413.14 (\emph{SD} = 1076.37).

\section{Results}

Analyses were conducted in the same manner as the first part of the study with bootstrapped means and CIs calculated for the seven categories marking attention. Results can be seen as a forest plot in Figure \ref{fig:Kpic} and Table \ref{tab:Ktable}. For the Senate, Hypothesis 1 was not supported. The effect was not in the hypothesized direction and was not of the hypothesized magnitude. Hypothesis 2 was supported with legislators opposing the war measure displaying higher internal focus than legislators supporting the war measure with a somewhat stronger effect size magnitude of that hypothesized. Hypothesis 3 was partially supported. Supporters of the war measure tended to show lower cognitive complexity than those who opposed it, but the effect was slightly weaker than expected.

\section{Discussion}

The results of this first study fail to provide consistent, strong support for any of our hypotheses. Hypothesis 3 was most strongly supported. Those supporting the war measures were less cognitively complex than those opposing them. However, in the case of the Senate, the effect was somewhat weaker than expected. The results were inconsistent for Hypothesis 1 and 2 (supporters of war measures would be more externally focus while those opposing would be internally focused) in that effects found for the House and Senate are non-overlapping. For Hypothesis 1, supporters of war in the House were marginally more externally focused (the effect was smaller than expected) but the effect was not replicated for the Senate. For Hypothesis 2, those opposing the measure in the Senate were more internally focused with an effect size larger than expected, but the same could not be said for those in the House where the opposite effect was found.
It is difficult to know exactly why this is the case; however there are several possible explanations. First, voting in Congress is exceedingly complex and is influenced by much more than floor debates in a given chamber. In this case, the Senate vote on the resolution occurred before the main debate in the House, which may have influenced what the debate focused on. Second, the Senate and the House are composed differently. Members of the House serve two year terms while Senators serve six year terms. Furthermore, Senators typically have more political experience than members of the House. These, as well as other factors, may help explain the differential effects for the two chambers of Congress.

Based on the findings of Abe (2012) and Matsumoto, Frank, and Hwang (2015), we expected more consistent support for our hypotheses. However, the results could also be explained by the situation posed by the particular resolution. In this conflict, rather than responding to an act of aggression or a perceived threat, the U.S. was deciding the extent to which the U.S. would be involved in ongoing NATO (a treaty organization of which the U.S. is a member) operations in Kosovo and Serbia. It is possible that some viewed the outgroup as NATO rather than Serbians. In this case, with no clear, immediate threat to the U.S., for those making ingroup-outgroup distinctions, protecting the ingroup may have meant opposing the war rather than supporting it. In order to determine if the situation surrounding the Kosovo conflict may have impacted the first study, we next turned to examine the Iraq War which had more support and also represented a possible clear threat to the U.S.

\section{Study 2A - Iraq in the House}

In this next study, we examined the debate preceding the congressional approval of the use of military force against Iraq. Regime change had been a long-standing position of the U.S. toward Iraq following the Gulf War; however serious military action was not considered until after the World Trade Center attacks on September 11, 2001. In 2002, President Bush declared Iraq part of an \enquote{axis of evil} in his State of the Union address. Iraq's repeated violations of nuclear arms agreements, ties to terrorist organizations, and pursuit of weapons of mass destruction were argued by the Bush Administration to potentially pose a major threat to U.S. national security. This prompted the debate within Congress as to whether or not to approve President Bush's request for military action (\cite{Katzman2002}). These studies were used to determine if the findings from the first study extend to a different conflict. Specifically, in the first part of this study, we examined the debate in the House of Representatives to determine if members of Congress who supported taking military action used more self and future references.

\section{Method}

Once again using the Government Publishing Office, we collected speeches given in the House of Representatives pertaining to the use of U.S. military force against Iraq in the three months before the vote on House Joint Resolution 114 on October 10, 2002. This bill passed the House with a 296-133 majority; with most Republicans supporting the measure and 60\% of Democrats opposing. A total of 274 speeches were collected representing 233 unique speakers. Of these speeches, 155 speeches were made by Democrats, 119 were made by Republicans. The average word count of the speeches was 742.34 (\emph{SD} = 1053.45). Four speeches were excluded for no voting record.

\section{Results}

\begin{table}[htbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:Itable}Descriptive statistics for each dependent variable by chamber for Iraq}

\small{

\begin{tabular}{lccccccccc}
\toprule
Chamber & Region & DV & $M_O$ & $SD_O$ & $M_S$ & $SD_S$ & $d_s$ & $d_s$ LL & $d_s$ UL\\
\midrule
House & 1 & She/He & 0.56 & 0.68 & 1.17 & 1.14 & -0.63 & -0.87 & -0.38\\
House & 1 & They & 0.46 & 0.61 & 0.54 & 0.71 & -0.12 & -0.37 & 0.12\\
House & 1 & External & 1.02 & 0.97 & 1.71 & 1.33 & -0.58 & -0.83 & -0.33\\
Senate & 1 & She/He & 0.60 & 0.57 & 1.20 & 0.79 & -0.82 & -1.20 & -0.44\\
Senate & 1 & They & 0.48 & 0.41 & 0.56 & 0.50 & -0.17 & -0.54 & 0.20\\
Senate & 1 & External & 1.08 & 0.72 & 1.77 & 1.01 & -0.74 & -1.12 & -0.36\\
House & 2 & I & 1.67 & 1.63 & 1.83 & 1.43 & -0.11 & -0.35 & 0.13\\
House & 2 & We & 3.00 & 1.98 & 2.76 & 1.71 & 0.13 & -0.11 & 0.37\\
House & 2 & Internal & 4.67 & 2.43 & 4.59 & 2.27 & 0.03 & -0.21 & 0.27\\
Senate & 2 & I & 1.98 & 1.49 & 1.98 & 1.92 & 0.00 & -0.37 & 0.37\\
Senate & 2 & We & 2.53 & 1.20 & 2.61 & 1.41 & -0.06 & -0.42 & 0.31\\
Senate & 2 & Internal & 4.53 & 1.78 & 4.61 & 2.23 & -0.04 & -0.40 & 0.33\\
House & 3 & Complexity & 0.69 & 3.63 & -0.57 & 3.37 & 0.36 & 0.12 & 0.61\\
Senate & 3 & Complexity & 0.32 & 3.89 & -0.18 & 3.75 & 0.13 & -0.23 & 0.50\\
\bottomrule
\addlinespace
\end{tabular}

}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} Confidence intervals for $d_s$, which are standardized mean differences, were calculated using 
          non-central $t$ distribution. O = Oppose, S = Support, LL = Lower Limit, UL = Upper Limit.}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}

\begin{figure}
\centering
\includegraphics{Language-of-War-Markdown_KJ2_files/figure-latex/Ipic-1.pdf}
\caption{\label{fig:Ipic}House (left) and Senate (right) bootstrapped means and 95\% confidence interval of each linguistic category for Iraq.}
\end{figure}

As in the first study, bootstrapped means and confidence intervals as well as effect sizes (Cohen's \(d_s\)) were calculated for speeches of those supporting the measure versus those opposing the measure for the following LIWC categories: first-person singular (\emph{I}), first-person plural (\emph{we}), third-person singular (\emph{he}, \emph{she}), third-person plural (\emph{they}) as well as composite measure for external focus, internal focus, and cognitive complexity. Results can be seen as a forest plot in Figure \ref{fig:Ipic} and in Table \ref{tab:Itable}. Support was found for Hypothesis 1. Legislators supporting the war measure were more externally focused and the effect size magnitude somewhat larger than that hypothesized. The largest differences was in third-person singular pronouns (\emph{he}). Hypothesis 2 was very weakly supported; the effect was in the right direction, but magnitude of the effect was much smaller (0.03) than hypothesized. Hypothesis 3 was supported; supporters of the war measure were less cognitively complex than those who opposed it with the hypothesized magnitude.


\section{Study 2B - Iraq in the Senate}

In the second part of this study, we examined the debate in the Senate. We wished to determine if, like senators who opposed military action in Kosovo, senators who opposed action against Iraq used more group references as well as more reference to current events or if senators were more like House members debating Iraq.

\section{Method}

In this part of the study, speeches from the Senate were gathered for the 6 months before the Senate vote on House Joint Resolution 114 conducted on October 11, 2002. The bill passed with a 77-23 majority. All but one Republican supported the measure as did 58\% of Democrats. In total, 138 speeches were collected representing 85 unique speakers. Of these speeches, 74 were given by Democrats and 64 by Republicans. The average word count for these speeches were 1991.23 (\emph{SD} = 1671.70).

\section{Results}

Analyses were conducted in the same manner as the first part of the study to determine differences between supporters and opponents of military action in Iraq in terms of the use of first-person singular (\emph{I}), first-person plural (\emph{we}), third-person singular (\emph{he}, \emph{she}), third-person plural (\emph{they}) as well as composite measure for external focus, internal focus, and cognitive complexity. Figure \ref{fig:Ipic} displays these results as a forest plot, and all values are in Table \ref{tab:Itable}. Hypothesis 1 was once again supported. Senators supporting the war legislation were more externally focus, and like in the House, tended to use third-person singular pronouns (\emph{he}) at higher rates. The magnitude of the effect was slightly larger than hypothesized. Once again, we failed to find support for Hypothesis 2 with no differences found in internal focus with both the direction and magnitude of the effect not matching our hypothesis. Finally, cognitive complexity tended to be lower for Senators supporting the war measure providing at least partial support for Hypothesis 3 (the effect was weaker than hypothesized).

\section{Discussion}

The results from this second study more closely matched our hypotheses. For both the House and Senate, members of Congress who supported taking military action were more externally focused than those who opposed taking military action. Interestingly, the difference in external focus was driven by third person singular pronouns (\emph{he}) rather than third person plural pronouns (\emph{they}). Although this finding was not quite expected, these differences make sense in light of the situation. In the case of the Iraq War, the threat was seen not as a group of people but rather a single individual, Saddam Hussein. The second hypothesis was not supported. In both the House and Senate, legislators who opposed the war measure were not more internally focused than those who supported it. As was stated previously, this difference in results could be due to voting procedures or compositional differences in the House and Senate. Finally, our third hypothesis was once again consistently supported with the only caveat being the effect was slightly weaker than expected in the Senate. Those who supported the war measures showed less cognitive complexity than those who opposed them in both the House and Senate.

As a final test of our hypotheses, we examined the Congressional debate surrounding U.S. involvement in Libya during its 2011 civil war. We might expect to find similar results to Study 1 as, like the Kosovo war, there was less support for U.S. military involvement as well as a lack of a perceived clear, immediate threat to the U.S.

\section{Study 3 - Libya in the House}

In this final study, we examine the debate in the House of Representatives surrounding U.S. military involvement in Libya during its revolution. In February 2011, a revolt against Libyan dictator, Muammar Qaddafi, prompted the intervention of NATO when Qaddafi violently suppressed all opposition. The involvement of NATO lead to debate within Congress as to the exact role of the U.S. in military operations in Libya and the extent of U.S involvement (\cite{Blanchard2011}). In examining this debate, we wished to determine if the language of those who supported or opposed military action was similar to those of either of the first two studies.

\section{Method}

In this final study, the Congressional Record was searched for speeches given in the House of Representatives pertaining to the debate of the authorization of military action against Libya in the three months before the vote on House Joint Resolution 68 on June 24, 2011. The bill failed in the House 123-295. All but 14 Republicans voted against the resolution while 60\% of Democrats supported the resolution. A total of 104 speeches were collected representing 76 unique speakers. Democrats made 53 of these speeches while 51 speeches were made by Republicans. The average word count for these speeches was 465.93 (\emph{SD} = 477.41). As the resolution failed in the House, it was not possible to examine this debate in the Senate. Five speeches were excluded for no voting record.

\section{Results}

\begin{table}[htbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:Ltable}Descriptive statistics for each dependent variable by chamber for Libya}

\small{

\begin{tabular}{lccccccccc}
\toprule
Chamber & Region & DV & $M_O$ & $SD_O$ & $M_S$ & $SD_S$ & $d_s$ & $d_s$ LL & $d_s$ UL\\
\midrule
House & 1 & She/He & 0.60 & 0.97 & 0.65 & 1.05 & -0.05 & -0.47 & 0.37\\
House & 1 & They & 0.61 & 1.10 & 0.62 & 0.84 & -0.01 & -0.43 & 0.41\\
House & 1 & External & 1.21 & 1.63 & 1.24 & 1.47 & -0.02 & -0.44 & 0.40\\
House & 2 & I & 2.42 & 1.96 & 2.32 & 1.40 & 0.06 & -0.36 & 0.48\\
House & 2 & We & 2.95 & 1.67 & 2.90 & 2.31 & 0.03 & -0.39 & 0.45\\
House & 2 & Internal & 5.35 & 2.13 & 5.19 & 2.54 & 0.07 & -0.35 & 0.49\\
House & 3 & Complexity & 0.36 & 3.92 & -0.78 & 3.75 & 0.30 & -0.12 & 0.71\\
\bottomrule
\addlinespace
\end{tabular}

}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} Confidence intervals for $d_s$, which are standardized mean differences, were calculated using 
          non-central $t$ distribution. O = Oppose, S = Support, LL = Lower Limit, UL = Upper Limit.}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}

\begin{figure}
\centering
\includegraphics{Language-of-War-Markdown_KJ2_files/figure-latex/Lpic-1.pdf}
\caption{\label{fig:Lpic}House (left) and Senate (right) bootstrapped means and 95\% confidence interval of each linguistic category for Libya.}
\end{figure}

As in the first two studies, analyses consisted on comparing the bootstrapped means, CIs, and effects sizes for those who supported the military measure versus those who opposed it. These results are displayed in Figure \ref{fig:Lpic} as a forest plot and in Table \ref{tab:Ltable}. For Hypotheses 1 and 2, the effects were in the hypothesized direction, but magnitude of the effects were much weaker than hypothesized. Hypothesis 3 was most strongly supported with an effect size in the right direction and nearly as strong as hypothesized.

\section{Discussion}

The relatively small sample size limited the power of the study, but trends in each case were in the hypothesized direction, although the results were weak. In addition to potentially limited power, our finding from Studies 1 and 3 could indicate that in situations where there is less Congressional support for military action and no clear, immediate threat to the U.S., the difference between support and opposition for military action is not a matter of attentional focus but rather other social and political forces.

\section{General Discussion}

Across all three studies, we found consistent evidence that supporters of war measures show less cognitive complexity in their speeches than those on the opposing side (Hypothesis 3) replicating part of the Matsumoto et al. (\citeyear{Matsumoto2013}) study. When it comes to consideration of aggressive acts like war, our studies would suggest that legislators (at least in the U.S.) reason similarly to the executive leaders analyzed by Matsumoto et al. (\citeyear{Matsumoto2013}) though our findings suggest the effect may be slightly weaker among legislators. Political figures in favor of aggressive measures seek to simplify the debate whereas those against aggressive measure may seek to consider the issue more deeply. Whether the decreased cognitive complexity before aggression is a rhetorical strategy, ideological beliefs, cognitive style, or some other factor is worth further investigation.

Our hypotheses regarding internal and external focus were not consistently supported. Strong support for Hypothesis 1 was found only in the case of the debate around the Iraq War. Weak support was found in the debates around Kosovo and Libya in the House. Interestingly, the Iraq War legislation was the only of our case in our three studies which received majority support in both the House and Senate. Differences in external focus may depend partially on the aggressive act having the support of the majority or having popular support or there being a potentially immediate, clear threat to the U.S. legislators could point to. In the cases of Kosovo and Libya, legislators may have supported the war measures for reasons other than aggression such as to support the president's agenda weakening or reversing the hypothesized effect.

Hypothesis 2 received the weakest, most inconsistent support of any of our hypotheses with strong evidence for the effect found only in the Senate debate of the Kosovo resolution failing to replicate Abe (\citeyear{Abe2012}). Unlike Hypotheses 1 and 3 which are at least partially based in Matsumoto et al. (\citeyear{Matsumoto2013})'s study of executive, Hypothesis 2 is solely based in Abe (\citeyear{Abe2012})'s study of the war attitudes of ordinary citizens. Our results suggest that findings of Abe (\citeyear{Abe2012}) may only generalize to laypeople and fail to capture the processes at work with the war decisions of political elites.

Additionally, we may have weak support for Matsumoto et al. (\citeyear{Matsumoto2013}) is due to changes in the dynamics of war. While Matsumoto et al. (\citeyear{Matsumoto2013}) examined events spanning 1830 to 2010, our study focused on three recent conflicts within the context of U.S. legislator bodies. Historically, the U.S. would declare war on another nation (i.e., fighting the Germans in WWI). In WWII, a slight shift occurred where the U.S. was fighting not only another nation but also an ideology (Nazi Germany, Fascist Italy). With the beginning of the Cold War, another movement happened where the U.S. did not directly fight another nation (USSR) but instead fought indirectly with proxy wars (Korean War, Vietnam War) while battling against enemy ideology (Communism). After the Cold War and the fall of the Soviet Union, the focus shifted to the United States' main conflict being the war on terror in which there is no official, recognized government or nation with which to negotiate (\cite{Matthews2014}). Furthermore, Balas, Owsiak, and Diehl (\citeyear{Balas2012}) argued that one possible motivation for war, since the end of the Cold War, was the increased emphasis on the international norms of democratization and humanitarianism. Hence, rather than capturing solely support for aggressive actions, our study of congressional debates in this context may have also captured legislators' attitudes toward humanitarianism, globalization, and terrorism. Further work would be necessary to the different reasons why political figures might support or oppose a war measure.

\subsection{Limitations}

The sample and methods used in the study, while useful, can also be somewhat limited in scope. First, even though the Congressional Record represents everything said on the floor of Congress, it does not necessarily represent the entirety of Congress. Our sample incorporates nearly 15 years in Congress. This time period encompassed seven election cycles and at any given time, there are 100 senators and 435 congressmen and women. While our data set likely included speeches from the more influential senators and congressmen and women, we cannot predict voting from those who did not speak. Furthermore, our findings regarding masculine versus feminine pronouns could be confounded by the under-representation of women in Congress. In the 113th Congress, women comprised 20\% of the Senate and 18\% of the House (\cite{Manning2014}). For the years of voting records we used, there were 96 women in Congress in 2011, 73 in 2002, and 67 in 1999 compared to 105 women in the current Congress. Another limitation is tied to using word frequency as an independent measure, although Tausczik and Pennebaker (\citeyear{Tausczik2011}) have provided support for this research. Word frequency is a meaningful measure of language, though it does fail to take into account context, sarcasm, and other subtle aspects of language.

\subsection{Future Directions}

While we were unable to completely replicate the previous studies, the method used has great potential for replicating past work on political behaviors and attitudes in a legislative context as well as enhancing the understanding of legislative decision making. We examined only one small area of policy using a single psychological process, but future research could explore foreign policy more widely or education policy or any number of legislative areas where there is recurrent debate. Furthermore, our investigation was limited to studying attentional focus and cognitive complexity, but with LIWC2015 or other language analysis methods, future research could examine thinking style, emotionality, authenticity, cognitive processing, or any number of other psychological constructs. When it comes to politics there is no lack of political language, making language analysis a powerful tool for political psychology, especially when combined with other behavioral data such as voting records.

\subsection{Author Contact}
Correspondence concerning this article should be addressed to Dr. Kayla N. Jordan, 326 Market St, Harrisburg, PA 17101. E-mail: kjordan@harrisburgu.edu}

\subsection{Conflict of Interest and Funding}
Authors have no conflicts of interest to declare. No funding was used for this project.

\subsection{Author Contributions}
- Conceptualization: KJ
- Writing - Original Draft Preparation: KJ, EB, WP
- Writing - Review & Editing: KJ, EB
- Data curation: KJ
- Formal analysis: KJ, EB, WP
- Methodology: KJ, EB, WP

\printbibliography

\end{document}
